version: '3.8'

services:
  auto-claude:
    build:
      context: .
      dockerfile: Dockerfile.auto-claude
    container_name: spacepunk-auto-claude
    volumes:
      # Mount the entire project as read-only, except for output directories
      - .:/workspace/spacepunk:ro
      # Mount specific writable directories
      - ./auto-claude-output:/workspace/output
      - ./auto-claude-logs:/workspace/logs
      # Mount git directory for commits (careful!)
      - ./.git:/workspace/spacepunk/.git
      # Mount Claude CLI from host system  
      - /Users/ejfox/.nvm/versions/node/v20.16.0/bin/claude:/usr/local/bin/claude:ro
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - NODE_ENV=development
    working_dir: /workspace/spacepunk
    restart: unless-stopped
    # Resource limits for safety
    mem_limit: 2g
    cpus: '1.0'
    # Network isolation (optional)
    network_mode: "bridge"
    # Security settings
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem for extra security
    read_only: false  # We need write access for git operations
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    command: ["sleep", "infinity"]  # Keep container running for manual login
    stdin_open: true
    tty: true

  # Optional: monitoring container
  monitoring:
    image: alpine:latest
    container_name: spacepunk-monitor
    volumes:
      - ./auto-claude-logs:/logs:ro
    command: |
      sh -c "
        while true; do
          echo '[MONITOR] Auto-Claude Status Check:'
          if [ -f /logs/auto-claude.pid ]; then
            echo '[MONITOR] Auto-Claude appears to be running'
          else
            echo '[MONITOR] Auto-Claude PID file not found'
          fi
          echo '[MONITOR] Recent log activity:'
          tail -5 /logs/auto-claude-*.log 2>/dev/null || echo '[MONITOR] No logs found'
          echo '---'
          sleep 300  # Check every 5 minutes
        done
      "
    restart: unless-stopped
    depends_on:
      - auto-claude