version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: spacepunk-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-spacepunk}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-spacepunk_dev}
      POSTGRES_DB: ${POSTGRES_DB:-spacepunk_logi}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-spacepunk}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: spacepunk-server
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3001}
      DATABASE_URL: postgres://${POSTGRES_USER:-spacepunk}:${POSTGRES_PASSWORD:-spacepunk_dev}@postgres:5432/${POSTGRES_DB:-spacepunk_logi}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-development_secret_change_in_production}
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: spacepunk-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: